# Travis's native R Image (http://docs.travis-ci.com/user/languages/r/)
language: r
cache: packages
warnings_are_errors: true
os:
  - linux
  - windows
dist: focal

jobs:
  include:
    - name: linux-focal
      os: linux
      dist: focal
      env: R_CODECOV=true
    - name: windows-focal
      os: windows
      dist: focal
      env: R_CODECOV=false
    # - name: osx-current
    #   os: osx
    #   # addons:
    #   #   homebrew:
    #   #     packages: curl
    #   # before_install:
    #   #   - brew install curl
    #   #   - brew link --force curl
    #   latex: false
    #   r_build_args: '--no-build-vignettes'
    #   r_check_args: '--ignore-vignettes --no-examples'

r_github_packages:
  - r-lib/covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then Rscript -e 'covr::codecov()'; fi
  # - Rscript -e 'covr::coveralls()'
